use_frameworks!

target 'MyLibrary_Example' do
  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
  end

  pod 'MyLibrary', :path => '../'

  target 'MyLibrary_Tests' do
    inherit! :search_paths
    
  end
end
